services:
  - type: web
    name: cash-sense-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false # Cette variable sera configurée manuellement dans le dashboard de Render
